rm(list=ls())
library(vegan)
Families<-read.csv("family_totals.csv",header=TRUE,row.names=1)
propFamily<-decostand(Families,"total")
logFamily<-log(Families+1)
NALMA<-c(1:8)
Total<-Families[23, ]
logTotal<-logFamily[23, ]
FamilyNames<-Families[1:22, ]
labels=c("Hemingfordian","Barstovian","Clarendonian","Hemphillian","Blancan","Irivngtonian","Rancholabrean","Holocene")

x<-1
y<-1
x1<-c(1:8,8:1)
y1<-c(logFamily[1, ],0,0,0,0,0,0,0,0)
x2<-c(1:8,8:1)
y2<-c((logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]))
x3<-c(1:8,8:1)
y3<-c((logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]))
x4<-c(1:8,8:1)
y4<-c((logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]))
x5<-c(1:8,8:1)
y5<-c((logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]))
x6<-c(1:8,8:1)
y6<-c((logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]))
x7<-c(1:8,8:1)
y7<-c((logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]))
x8<-c(1:8,8:1)
y8<-c((logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]))
x9<-c(1:8,8:1)
y9<-c((logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]))
x10<-c(1:8,8:1)
y10<-c((logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]))
x11<-c(1:8,8:1)
y11<-c((logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]))
x12<-c(1:8,8:1)
y12<-c((logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]))
x13<-c(1:8,8:1)
y13<-c((logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]))
x14<-c(1:8,8:1)
y14<-c((logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]))
x15<-c(1:8,8:1)
y15<-c((logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]))
x16<-c(1:8,8:1)
y16<-c((logFamily[16, ]+logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]+logFamily[15, ]))
x17<-c(1:8,8:1)
y17<-c((logFamily[17, ]+logFamily[16, ]+logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]+logFamily[15, ]+logFamily[16, ]))
x18<-c(1:8,8:1)
y18<-c((logFamily[18, ]+logFamily[17, ]+logFamily[16, ]+logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]+logFamily[15, ]+logFamily[16, ]+logFamily[17, ]))
x19<-c(1:8,8:1)
y19<-c((logFamily[19, ]+logFamily[18, ]+logFamily[17, ]+logFamily[16, ]+logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]+logFamily[15, ]+logFamily[16, ]+logFamily[17, ]+logFamily[18, ]))
x20<-c(1:8,8:1)
y20<-c((logFamily[20, ]+logFamily[19, ]+logFamily[18, ]+logFamily[17, ]+logFamily[16, ]+logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]+logFamily[15, ]+logFamily[16, ]+logFamily[17, ]+logFamily[18, ]+logFamily[19, ]))
x21<-c(1:8,8:1)
y21<-c((logFamily[21, ]+logFamily[20, ]+logFamily[19, ]+logFamily[18, ]+logFamily[17, ]+logFamily[16, ]+logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]+logFamily[15, ]+logFamily[16, ]+logFamily[17, ]+logFamily[18, ]+logFamily[19, ]+logFamily[20,]))
x22<-c(1:8,8:1)
y22<-c((logFamily[22, ]+logFamily[21, ]+logFamily[20, ]+logFamily[19, ]+logFamily[18, ]+logFamily[17, ]+logFamily[16, ]+logFamily[15, ]+logFamily[14, ]+logFamily[13, ]+logFamily[12, ]+logFamily[11, ]+logFamily[10, ]+logFamily[9, ]+logFamily[8, ]+logFamily[7, ]+logFamily[6, ]+logFamily[5, ]+logFamily[4, ]+logFamily[3, ]+logFamily[2, ]+logFamily[1, ]),rev(logFamily[1, ]+logFamily[2, ]+logFamily[3, ]+logFamily[4, ]+logFamily[5, ]+logFamily[6, ]+logFamily[7, ]+logFamily[8, ]+logFamily[9, ]+logFamily[10, ]+logFamily[11, ]+logFamily[12, ]+logFamily[13, ]+logFamily[14, ]+logFamily[15, ]+logFamily[16, ]+logFamily[17, ]+logFamily[18, ]+logFamily[19, ]+logFamily[20,]+logFamily[21, ]))

par(mfrow=c(1,2),mar=c(6,4,1,1))
plot(NALMA,y=c(1:8),type="n",ylim=c(0,60),ylab="Log Number of Occurrences",xlab=NA,xaxt="n") 
axis(1, at=NALMA, labels=FALSE)
text(x=NALMA, y=par()$usr[3]-0.1*(par()$usr[4]-par()$usr[3]),labels=labels, srt=45, adj=0.8, xpd=TRUE)
polygon(x1,y1,col="mediumaquamarine")
polygon(x2,y2,col="limegreen")
polygon(x3,y3,col="magenta")
polygon(x4,y4,col="blue")
polygon(x5,y5,col="mediumorchid")
polygon(x6,y6,col="orange")
polygon(x7,y7,col="navy")
polygon(x8,y8,col="moccasin")
polygon(x9,y9,col="palegreen")
polygon(x10,y10,col="palevioletred")
polygon(x11,y11,col="pink")
polygon(x12,y12,col="purple")
polygon(x13,y13,col="red")
polygon(x14,y14,col="royalblue")
polygon(x15,y15,col="hotpink")
polygon(x16,y16,col="seagreen")
polygon(x17,y17,col="skyblue")
polygon(x18,y18,col="tomato")
polygon(x19,y19,col="tan4")
polygon(x20,y20,col="yellow")
polygon(x21,y21,col="darkgreen")
polygon(x22,y22,col="slategray2")

plot(x,y,xaxt="n", yaxt="n", col="white", frame=FALSE, xlab="", ylab="")
legend("left",fill=c("mediumaquamarine","limegreen","magenta","blue","mediumorchid","orange","navy","moccasin","palegreen","palevioletred","pink","purple","red","royalblue","hotpink","seagreen","skyblue","tomato","tan4","yellow","darkgreen","slategray2"),c(rownames(FamilyNames)),cex=0.85)